# -*- coding: utf-8 -*-
"""Predicting ship fuel Efficiency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rwhyqk8UDEsDbqqOfdc6ni53tXFKTt0q
"""



"""# Task
Create a Streamlit application to predict ship fuel efficiency based on the data in "ship_fuel_efficiency.csv".

## Load the data

### Subtask:
Load the `ship_fuel_efficiency.csv` file into a pandas DataFrame.

**Reasoning**:
Load the data into a pandas DataFrame and display the first few rows.
"""

import pandas as pd

##df = pd.read_csv('ship_fuel_efficiency.csv')
##display(df.head())

df = pd.read_csv('ship_fuel_efficiency.csv')
    ##st.write("First few rows of the data:")
    ##st.dataframe(df.head())

"""## Data preprocessing

### Subtask:
Prepare the data for the model. This includes handling categorical variables (e.g., using one-hot encoding), scaling numerical features, and splitting the data into training and testing sets.

**Reasoning**:
Prepare the data for model training by identifying categorical and numerical features, applying one-hot encoding to categorical features, scaling numerical features, and splitting the data into training and testing sets.
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Identify categorical and numerical columns
categorical_features = ['ship_type', 'route_id', 'month', 'fuel_type', 'weather_conditions']
numerical_features = ['distance', 'fuel_consumption', 'CO2_emissions']

# Separate features (X) and target (y)
X = df.drop('engine_efficiency', axis=1)
y = df['engine_efficiency']

# Create a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough' # Keep other columns (like ship_id) if any, although not needed for training
)

# Create a pipeline for preprocessing
X_processed = preprocessor.fit_transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42)

print("Data preprocessing complete. Shapes of the resulting datasets:")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""## Model selection and training

### Subtask:
Choose a suitable regression model (since efficiency is likely a continuous variable) and train it on the prepared data.

**Reasoning**:
Import the Linear Regression model and train it on the preprocessed training data.
"""

from sklearn.linear_model import LinearRegression

# Instantiate the Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

print("Linear Regression model trained successfully.")

"""**Reasoning**:
The error message "ValueError: could not convert string to float: 'NG096'" indicates that there is still a non-numeric column ('ship_id') in the data being fed to the model. The 'ship_id' column was kept in the preprocessor with `remainder='passthrough'`. It should be excluded from the training data.


"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Identify categorical and numerical columns, excluding 'ship_id' from features
categorical_features = ['ship_type', 'route_id', 'month', 'fuel_type', 'weather_conditions']
numerical_features = ['distance', 'fuel_consumption', 'CO2_emissions']
# The column 'ship_id' is not a feature for the model, so we won't include it in the preprocessor

# Separate features (X) and target (y)
X = df.drop(['engine_efficiency', 'ship_id'], axis=1) # Drop 'ship_id' from features
y = df['engine_efficiency']

# Create a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough' # There should be no remaining columns now
)

# Create a pipeline for preprocessing
X_processed = preprocessor.fit_transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42)

# Instantiate the Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

print("Linear Regression model trained successfully.")

"""## Model evaluation

### Subtask:
Evaluate the trained model's performance using appropriate regression metrics (e.g., Mean Absolute Error, Mean Squared Error, R-squared).

**Reasoning**:
Evaluate the trained model's performance using appropriate regression metrics.
"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate regression metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the metrics
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"R-squared (R2): {r2:.4f}")

"""## Save the model and scaler

### Subtask:
Save the trained model and the scaler object (if used) to files for later use in the Streamlit application.

**Reasoning**:
Import the joblib library and save the trained model and the preprocessor object to files.
"""

import joblib

# Save the trained model
joblib.dump(model, 'linear_regression_model.joblib')

# Save the preprocessor object
joblib.dump(preprocessor, 'preprocessor.joblib')

print("Model and preprocessor saved successfully.")

"""## Create streamlit app code

### Subtask:
Write the Python code for the Streamlit application. This will involve loading the saved model and scaler, creating a user interface for inputting ship parameters, preprocessing the input data, making a prediction, and displaying the predicted efficiency.

**Reasoning**:
Write the Python code for the Streamlit application, including loading the model and preprocessor, creating the UI, handling input, preprocessing, predicting, and displaying the result.
"""

import streamlit as st
import joblib
import pandas as pd

# Load the saved model and preprocessor
try:
    model = joblib.load('linear_regression_model.joblib')
    preprocessor = joblib.load('preprocessor.joblib')
except FileNotFoundError:
    st.error("Model or preprocessor file not found. Please ensure 'linear_regression_model.joblib' and 'preprocessor.joblib' are in the same directory.")
    st.stop()

# Set up the Streamlit app title and description
st.title('Ship Fuel Efficiency Prediction')
st.write('Enter the ship parameters to predict the engine efficiency.')

# Define the features used in the model (excluding 'ship_id' and 'engine_efficiency')
features = ['ship_type', 'route_id', 'month', 'distance', 'fuel_type', 'fuel_consumption', 'CO2_emissions', 'weather_conditions']

# Get unique values for categorical features from the original dataframe (if available)
# This assumes you have access to the original df or know the unique values.
# For this example, we'll use placeholder lists. In a real app, load these from data or config.
ship_types = ['Oil Service Boat', 'Fishing Trawler', 'Cargo Ship', 'Tanker'] # Placeholder
route_ids = ['Warri-Bonny', 'Port Harcourt-Lagos', 'Lagos-Apapa'] # Placeholder
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] # Placeholder
fuel_types = ['HFO', 'Diesel'] # Placeholder
weather_conditions = ['Stormy', 'Moderate', 'Calm'] # Placeholder


# Create input widgets
st.sidebar.header('Ship Parameters')

ship_type = st.sidebar.selectbox('Ship Type', ship_types)
route_id = st.sidebar.selectbox('Route ID', route_ids)
month = st.sidebar.selectbox('Month', months)
distance = st.sidebar.number_input('Distance (km)', min_value=0.0, value=100.0)
fuel_type = st.sidebar.selectbox('Fuel Type', fuel_types)
fuel_consumption = st.sidebar.number_input('Fuel Consumption (liters)', min_value=0.0, value=2000.0)
co2_emissions = st.sidebar.number_input('CO2 Emissions (kg)', min_value=0.0, value=6000.0)
weather_conditions = st.sidebar.selectbox('Weather Conditions', weather_conditions)

# Create a button for prediction
if st.button('Predict Engine Efficiency'):
    # Collect user input into a DataFrame
    input_data = pd.DataFrame([[
        ship_type, route_id, month, distance, fuel_type, fuel_consumption, co2_emissions, weather_conditions
    ]], columns=features)

    # Ensure column order matches the training data features
    # This step is crucial if the order in the original data matters for the preprocessor
    # (e.g., if using ColumnTransformer with index-based selection).
    # If using name-based selection in ColumnTransformer, this might be less critical
    # but it's good practice.
    # For this example, assuming the order of features list is the correct order.
    input_data = input_data[features]


    # Apply the preprocessor to the input data
    # The preprocessor expects the same column names and order as the training data features
    try:
        input_processed = preprocessor.transform(input_data)
    except ValueError as e:
        st.error(f"Error during preprocessing: {e}. Please check if the input data matches the format expected by the preprocessor.")
        st.stop()


    # Make a prediction
    prediction = model.predict(input_processed)

    # Display the prediction
    st.subheader('Predicted Engine Efficiency')
    st.write(f'{prediction[0]:.2f}%')

"""**Reasoning**:
The previous command failed because the `streamlit` library is not installed. Install `streamlit` using pip.


"""
# Line 266: Delete this line
#!pip install streamlit

"""**Reasoning**:
Since the `streamlit` library is now installed, retry running the code to create the Streamlit application.


"""

import streamlit as st
import joblib
import pandas as pd

# Load the saved model and preprocessor
try:
    model = joblib.load('linear_regression_model.joblib')
    preprocessor = joblib.load('preprocessor.joblib')
except FileNotFoundError:
    st.error("Model or preprocessor file not found. Please ensure 'linear_regression_model.joblib' and 'preprocessor.joblib' are in the same directory.")
    st.stop()

# Set up the Streamlit app title and description
st.title('Ship Fuel Efficiency Prediction')
st.write('Enter the ship parameters to predict the engine efficiency.')

# Define the features used in the model (excluding 'ship_id' and 'engine_efficiency')
features = ['ship_type', 'route_id', 'month', 'distance', 'fuel_type', 'fuel_consumption', 'CO2_emissions', 'weather_conditions']

# Get unique values for categorical features from the original dataframe (if available)
# This assumes you have access to the original df or know the unique values.
# For this example, we'll use placeholder lists. In a real app, load these from data or config.
ship_types = ['Oil Service Boat', 'Fishing Trawler', 'Cargo Ship', 'Tanker'] # Placeholder
route_ids = ['Warri-Bonny', 'Port Harcourt-Lagos', 'Lagos-Apapa'] # Placeholder
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] # Placeholder
fuel_types = ['HFO', 'Diesel'] # Placeholder
weather_conditions = ['Stormy', 'Moderate', 'Calm'] # Placeholder


# Create input widgets
st.sidebar.header('Ship Parameters')

ship_type = st.sidebar.selectbox('Ship Type', ship_types)
route_id = st.sidebar.selectbox('Route ID', route_ids)
month = st.sidebar.selectbox('Month', months)
distance = st.sidebar.number_input('Distance (km)', min_value=0.0, value=100.0)
fuel_type = st.sidebar.selectbox('Fuel Type', fuel_types)
fuel_consumption = st.sidebar.number_input('Fuel Consumption (liters)', min_value=0.0, value=2000.0)
co2_emissions = st.sidebar.number_input('CO2 Emissions (kg)', min_value=0.0, value=6000.0)
weather_conditions = st.sidebar.selectbox('Weather Conditions', weather_conditions)

# Create a button for prediction
if st.button('Predict Engine Efficiency'):
    # Collect user input into a DataFrame
    input_data = pd.DataFrame([[
        ship_type, route_id, month, distance, fuel_type, fuel_consumption, co2_emissions, weather_conditions
    ]], columns=features)

    # Ensure column order matches the training data features
    # This step is crucial if the order in the original data matters for the preprocessor
    # (e.g., if using ColumnTransformer with index-based selection).
    # If using name-based selection in ColumnTransformer, this might be less critical
    # but it's good practice.
    # For this example, assuming the order of features list is the correct order.
    input_data = input_data[features]


    # Apply the preprocessor to the input data
    # The preprocessor expects the same column names and order as the training data features
    try:
        input_processed = preprocessor.transform(input_data)
    except ValueError as e:
        st.error(f"Error during preprocessing: {e}. Please check if the input data matches the format expected by the preprocessor.")
        st.stop()


    # Make a prediction
    prediction = model.predict(input_processed)

    # Display the prediction
    st.subheader('Predicted Engine Efficiency')
    st.write(f'{prediction[0]:.2f}%')

"""## Summary:

### Data Analysis Key Findings
*   The initial data was successfully loaded into a pandas DataFrame.
*   The data was preprocessed by separating features and target, applying `StandardScaler` to numerical features (`distance`, `fuel_consumption`, `CO2_emissions`), and applying `OneHotEncoder` to categorical features (`ship_type`, `route_id`, `month`, `fuel_type`, `weather_conditions`).
*   The preprocessed data was split into training (80%) and testing (20%) sets.
*   A Linear Regression model was successfully trained on the preprocessed training data after resolving an issue where the non-numeric 'ship\_id' column was initially included in the features.
*   The model's performance was evaluated on the test set, resulting in a Mean Absolute Error (MAE) of 6.0910, a Mean Squared Error (MSE) of 50.2468, and an R-squared (R2) of -0.0143.
*   The trained Linear Regression model and the preprocessor object were successfully saved to `linear_regression_model.joblib` and `preprocessor.joblib` files, respectively.
*   Python code for a Streamlit application was written to load the saved model and preprocessor, create a user interface for input, preprocess user input, make a prediction, and display the result.

### Insights or Next Steps
*   The current Linear Regression model performs poorly (indicated by the negative R-squared value), suggesting that a more complex model or further feature engineering might be needed to accurately predict ship fuel efficiency.
*   The Streamlit application code is ready to be deployed. The placeholder lists for categorical features should be replaced with actual unique values derived from the training data to ensure consistency with the preprocessor.

"""
